// <auto-generated/>
#pragma warning disable CS0618
using MealiMCP.Server.Api.Api.Parser.Ingredient;
using MealiMCP.Server.Api.Api.Parser.Ingredients;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MealiMCP.Server.Api.Api.Parser
{
    /// <summary>
    /// Builds and executes requests for operations under \api\parser
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ParserRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The ingredient property</summary>
        public global::MealiMCP.Server.Api.Api.Parser.Ingredient.IngredientRequestBuilder Ingredient
        {
            get => new global::MealiMCP.Server.Api.Api.Parser.Ingredient.IngredientRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ingredients property</summary>
        public global::MealiMCP.Server.Api.Api.Parser.Ingredients.IngredientsRequestBuilder Ingredients
        {
            get => new global::MealiMCP.Server.Api.Api.Parser.Ingredients.IngredientsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Parser.ParserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ParserRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/parser", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Parser.ParserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ParserRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/parser", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
