// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MealiMCP.Server.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AuthMethod
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Mealie")]
        #pragma warning disable CS1591
        Mealie,
        #pragma warning restore CS1591
        [EnumMember(Value = "LDAP")]
        #pragma warning disable CS1591
        LDAP,
        #pragma warning restore CS1591
        [EnumMember(Value = "OIDC")]
        #pragma warning disable CS1591
        OIDC,
        #pragma warning restore CS1591
    }
}
