// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MealiMCP.Server.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CheckAppConfig : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The baseUrlSet property</summary>
        public bool? BaseUrlSet { get; set; }
        /// <summary>The emailReady property</summary>
        public bool? EmailReady { get; set; }
        /// <summary>The enableOpenai property</summary>
        public bool? EnableOpenai { get; set; }
        /// <summary>The isUpToDate property</summary>
        public bool? IsUpToDate { get; set; }
        /// <summary>The ldapReady property</summary>
        public bool? LdapReady { get; set; }
        /// <summary>The oidcReady property</summary>
        public bool? OidcReady { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Models.CheckAppConfig"/> and sets the default values.
        /// </summary>
        public CheckAppConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.CheckAppConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MealiMCP.Server.Api.Models.CheckAppConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MealiMCP.Server.Api.Models.CheckAppConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "baseUrlSet", n => { BaseUrlSet = n.GetBoolValue(); } },
                { "emailReady", n => { EmailReady = n.GetBoolValue(); } },
                { "enableOpenai", n => { EnableOpenai = n.GetBoolValue(); } },
                { "isUpToDate", n => { IsUpToDate = n.GetBoolValue(); } },
                { "ldapReady", n => { LdapReady = n.GetBoolValue(); } },
                { "oidcReady", n => { OidcReady = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("baseUrlSet", BaseUrlSet);
            writer.WriteBoolValue("emailReady", EmailReady);
            writer.WriteBoolValue("enableOpenai", EnableOpenai);
            writer.WriteBoolValue("isUpToDate", IsUpToDate);
            writer.WriteBoolValue("ldapReady", LdapReady);
            writer.WriteBoolValue("oidcReady", OidcReady);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
