// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace MealiMCP.Server.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateRandomEntry : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The date property</summary>
        public Date? Date { get; set; }
        /// <summary>The entryType property</summary>
        public global::MealiMCP.Server.Api.Models.PlanEntryType? EntryType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Models.CreateRandomEntry"/> and sets the default values.
        /// </summary>
        public CreateRandomEntry()
        {
            AdditionalData = new Dictionary<string, object>();
            EntryType = global::MealiMCP.Server.Api.Models.PlanEntryType.Dinner;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.CreateRandomEntry"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MealiMCP.Server.Api.Models.CreateRandomEntry CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MealiMCP.Server.Api.Models.CreateRandomEntry();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "date", n => { Date = n.GetDateValue(); } },
                { "entryType", n => { EntryType = n.GetEnumValue<global::MealiMCP.Server.Api.Models.PlanEntryType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateValue("date", Date);
            writer.WriteEnumValue<global::MealiMCP.Server.Api.Models.PlanEntryType>("entryType", EntryType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
