// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MealiMCP.Server.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GroupStorage : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The totalStorageBytes property</summary>
        public int? TotalStorageBytes { get; set; }
        /// <summary>The totalStorageStr property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TotalStorageStr { get; set; }
#nullable restore
#else
        public string TotalStorageStr { get; set; }
#endif
        /// <summary>The usedStorageBytes property</summary>
        public int? UsedStorageBytes { get; set; }
        /// <summary>The usedStorageStr property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UsedStorageStr { get; set; }
#nullable restore
#else
        public string UsedStorageStr { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Models.GroupStorage"/> and sets the default values.
        /// </summary>
        public GroupStorage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.GroupStorage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MealiMCP.Server.Api.Models.GroupStorage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MealiMCP.Server.Api.Models.GroupStorage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "totalStorageBytes", n => { TotalStorageBytes = n.GetIntValue(); } },
                { "totalStorageStr", n => { TotalStorageStr = n.GetStringValue(); } },
                { "usedStorageBytes", n => { UsedStorageBytes = n.GetIntValue(); } },
                { "usedStorageStr", n => { UsedStorageStr = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("totalStorageBytes", TotalStorageBytes);
            writer.WriteStringValue("totalStorageStr", TotalStorageStr);
            writer.WriteIntValue("usedStorageBytes", UsedStorageBytes);
            writer.WriteStringValue("usedStorageStr", UsedStorageStr);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
