// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MealiMCP.Server.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GroupRecipeActionType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "link")]
        #pragma warning disable CS1591
        Link,
        #pragma warning restore CS1591
        [EnumMember(Value = "post")]
        #pragma warning disable CS1591
        Post,
        #pragma warning restore CS1591
    }
}
