// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MealiMCP.Server.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class IngredientUnitInput : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The abbreviation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Abbreviation { get; set; }
#nullable restore
#else
        public string Abbreviation { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The aliases property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MealiMCP.Server.Api.Models.IngredientUnitAlias>? Aliases { get; set; }
#nullable restore
#else
        public List<global::MealiMCP.Server.Api.Models.IngredientUnitAlias> Aliases { get; set; }
#endif
        /// <summary>The createdAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_createdAt? CreatedAt { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_createdAt CreatedAt { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The extras property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Extras { get; set; }
#nullable restore
#else
        public UntypedNode Extras { get; set; }
#endif
        /// <summary>The fraction property</summary>
        public bool? Fraction { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The pluralAbbreviation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_pluralAbbreviation? PluralAbbreviation { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_pluralAbbreviation PluralAbbreviation { get; set; }
#endif
        /// <summary>The pluralName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_pluralName? PluralName { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_pluralName PluralName { get; set; }
#endif
        /// <summary>The update_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_update_at? UpdateAt { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_update_at UpdateAt { get; set; }
#endif
        /// <summary>The useAbbreviation property</summary>
        public bool? UseAbbreviation { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Models.IngredientUnitInput"/> and sets the default values.
        /// </summary>
        public IngredientUnitInput()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.IngredientUnitInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MealiMCP.Server.Api.Models.IngredientUnitInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MealiMCP.Server.Api.Models.IngredientUnitInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "abbreviation", n => { Abbreviation = n.GetStringValue(); } },
                { "aliases", n => { Aliases = n.GetCollectionOfObjectValues<global::MealiMCP.Server.Api.Models.IngredientUnitAlias>(global::MealiMCP.Server.Api.Models.IngredientUnitAlias.CreateFromDiscriminatorValue)?.AsList(); } },
                { "createdAt", n => { CreatedAt = n.GetObjectValue<global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_createdAt>(global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_createdAt.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "extras", n => { Extras = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "fraction", n => { Fraction = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "pluralAbbreviation", n => { PluralAbbreviation = n.GetObjectValue<global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_pluralAbbreviation>(global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_pluralAbbreviation.CreateFromDiscriminatorValue); } },
                { "pluralName", n => { PluralName = n.GetObjectValue<global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_pluralName>(global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_pluralName.CreateFromDiscriminatorValue); } },
                { "update_at", n => { UpdateAt = n.GetObjectValue<global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_update_at>(global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_update_at.CreateFromDiscriminatorValue); } },
                { "useAbbreviation", n => { UseAbbreviation = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("abbreviation", Abbreviation);
            writer.WriteCollectionOfObjectValues<global::MealiMCP.Server.Api.Models.IngredientUnitAlias>("aliases", Aliases);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_createdAt>("createdAt", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteObjectValue<UntypedNode>("extras", Extras);
            writer.WriteBoolValue("fraction", Fraction);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_pluralAbbreviation>("pluralAbbreviation", PluralAbbreviation);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_pluralName>("pluralName", PluralName);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_update_at>("update_at", UpdateAt);
            writer.WriteBoolValue("useAbbreviation", UseAbbreviation);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::MealiMCP.Server.Api.Models.IngredientUnitInput_createdAtMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class IngredientUnitInput_createdAt : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.IngredientUnitInput_createdAtMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.IngredientUnitInput_createdAtMember1? IngredientUnitInputCreatedAtMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.IngredientUnitInput_createdAtMember1 IngredientUnitInputCreatedAtMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_createdAt"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_createdAt CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_createdAt();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.IngredientUnitInputCreatedAtMember1 = new global::MealiMCP.Server.Api.Models.IngredientUnitInput_createdAtMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(IngredientUnitInputCreatedAtMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(IngredientUnitInputCreatedAtMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.IngredientUnitInput_createdAtMember1>(null, IngredientUnitInputCreatedAtMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.IngredientUnitInput_pluralAbbreviationMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class IngredientUnitInput_pluralAbbreviation : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.IngredientUnitInput_pluralAbbreviationMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.IngredientUnitInput_pluralAbbreviationMember1? IngredientUnitInputPluralAbbreviationMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.IngredientUnitInput_pluralAbbreviationMember1 IngredientUnitInputPluralAbbreviationMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_pluralAbbreviation"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_pluralAbbreviation CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_pluralAbbreviation();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.IngredientUnitInputPluralAbbreviationMember1 = new global::MealiMCP.Server.Api.Models.IngredientUnitInput_pluralAbbreviationMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(IngredientUnitInputPluralAbbreviationMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(IngredientUnitInputPluralAbbreviationMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.IngredientUnitInput_pluralAbbreviationMember1>(null, IngredientUnitInputPluralAbbreviationMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.IngredientUnitInput_pluralNameMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class IngredientUnitInput_pluralName : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.IngredientUnitInput_pluralNameMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.IngredientUnitInput_pluralNameMember1? IngredientUnitInputPluralNameMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.IngredientUnitInput_pluralNameMember1 IngredientUnitInputPluralNameMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_pluralName"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_pluralName CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_pluralName();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.IngredientUnitInputPluralNameMember1 = new global::MealiMCP.Server.Api.Models.IngredientUnitInput_pluralNameMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(IngredientUnitInputPluralNameMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(IngredientUnitInputPluralNameMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.IngredientUnitInput_pluralNameMember1>(null, IngredientUnitInputPluralNameMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::MealiMCP.Server.Api.Models.IngredientUnitInput_update_atMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class IngredientUnitInput_update_at : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.IngredientUnitInput_update_atMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.IngredientUnitInput_update_atMember1? IngredientUnitInputUpdateAtMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.IngredientUnitInput_update_atMember1 IngredientUnitInputUpdateAtMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_update_at"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_update_at CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.IngredientUnitInput.IngredientUnitInput_update_at();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.IngredientUnitInputUpdateAtMember1 = new global::MealiMCP.Server.Api.Models.IngredientUnitInput_update_atMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(IngredientUnitInputUpdateAtMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(IngredientUnitInputUpdateAtMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.IngredientUnitInput_update_atMember1>(null, IngredientUnitInputUpdateAtMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
