// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MealiMCP.Server.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Mealie__schema__user__user__UserBase : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The admin property</summary>
        public bool? Admin { get; set; }
        /// <summary>The advanced property</summary>
        public bool? Advanced { get; set; }
        /// <summary>The authMethod property</summary>
        public global::MealiMCP.Server.Api.Models.AuthMethod? AuthMethod { get; set; }
        /// <summary>The canInvite property</summary>
        public bool? CanInvite { get; set; }
        /// <summary>The canManage property</summary>
        public bool? CanManage { get; set; }
        /// <summary>The canManageHousehold property</summary>
        public bool? CanManageHousehold { get; set; }
        /// <summary>The canOrganize property</summary>
        public bool? CanOrganize { get; set; }
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The fullName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_fullName? FullName { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_fullName FullName { get; set; }
#endif
        /// <summary>The group property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_group? Group { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_group Group { get; set; }
#endif
        /// <summary>The household property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_household? Household { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_household Household { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_id? Id { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_id Id { get; set; }
#endif
        /// <summary>The username property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_username? Username { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_username Username { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase"/> and sets the default values.
        /// </summary>
        public Mealie__schema__user__user__UserBase()
        {
            AdditionalData = new Dictionary<string, object>();
            AuthMethod = global::MealiMCP.Server.Api.Models.AuthMethod.Mealie;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "admin", n => { Admin = n.GetBoolValue(); } },
                { "advanced", n => { Advanced = n.GetBoolValue(); } },
                { "authMethod", n => { AuthMethod = n.GetEnumValue<global::MealiMCP.Server.Api.Models.AuthMethod>(); } },
                { "canInvite", n => { CanInvite = n.GetBoolValue(); } },
                { "canManage", n => { CanManage = n.GetBoolValue(); } },
                { "canManageHousehold", n => { CanManageHousehold = n.GetBoolValue(); } },
                { "canOrganize", n => { CanOrganize = n.GetBoolValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "fullName", n => { FullName = n.GetObjectValue<global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_fullName>(global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_fullName.CreateFromDiscriminatorValue); } },
                { "group", n => { Group = n.GetObjectValue<global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_group>(global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_group.CreateFromDiscriminatorValue); } },
                { "household", n => { Household = n.GetObjectValue<global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_household>(global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_household.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetObjectValue<global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_id>(global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_id.CreateFromDiscriminatorValue); } },
                { "username", n => { Username = n.GetObjectValue<global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_username>(global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_username.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("admin", Admin);
            writer.WriteBoolValue("advanced", Advanced);
            writer.WriteEnumValue<global::MealiMCP.Server.Api.Models.AuthMethod>("authMethod", AuthMethod);
            writer.WriteBoolValue("canInvite", CanInvite);
            writer.WriteBoolValue("canManage", CanManage);
            writer.WriteBoolValue("canManageHousehold", CanManageHousehold);
            writer.WriteBoolValue("canOrganize", CanOrganize);
            writer.WriteStringValue("email", Email);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_fullName>("fullName", FullName);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_group>("group", Group);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_household>("household", Household);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_id>("id", Id);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_username>("username", Username);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_fullNameMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Mealie__schema__user__user__UserBase_fullName : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_fullNameMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_fullNameMember1? MealieSchemaUserUserUserBaseFullNameMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_fullNameMember1 MealieSchemaUserUserUserBaseFullNameMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_fullName"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_fullName CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_fullName();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.MealieSchemaUserUserUserBaseFullNameMember1 = new global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_fullNameMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(MealieSchemaUserUserUserBaseFullNameMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(MealieSchemaUserUserUserBaseFullNameMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_fullNameMember1>(null, MealieSchemaUserUserUserBaseFullNameMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_groupMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Mealie__schema__user__user__UserBase_group : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_groupMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_groupMember1? MealieSchemaUserUserUserBaseGroupMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_groupMember1 MealieSchemaUserUserUserBaseGroupMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_group"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_group CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_group();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.MealieSchemaUserUserUserBaseGroupMember1 = new global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_groupMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(MealieSchemaUserUserUserBaseGroupMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(MealieSchemaUserUserUserBaseGroupMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_groupMember1>(null, MealieSchemaUserUserUserBaseGroupMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_householdMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Mealie__schema__user__user__UserBase_household : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_householdMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_householdMember1? MealieSchemaUserUserUserBaseHouseholdMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_householdMember1 MealieSchemaUserUserUserBaseHouseholdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_household"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_household CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_household();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.MealieSchemaUserUserUserBaseHouseholdMember1 = new global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_householdMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(MealieSchemaUserUserUserBaseHouseholdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(MealieSchemaUserUserUserBaseHouseholdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_householdMember1>(null, MealieSchemaUserUserUserBaseHouseholdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_idMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Mealie__schema__user__user__UserBase_id : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_idMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_idMember1? MealieSchemaUserUserUserBaseIdMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_idMember1 MealieSchemaUserUserUserBaseIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_id"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_id CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_id();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.MealieSchemaUserUserUserBaseIdMember1 = new global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_idMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(MealieSchemaUserUserUserBaseIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(MealieSchemaUserUserUserBaseIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_idMember1>(null, MealieSchemaUserUserUserBaseIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_usernameMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Mealie__schema__user__user__UserBase_username : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_usernameMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_usernameMember1? MealieSchemaUserUserUserBaseUsernameMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_usernameMember1 MealieSchemaUserUserUserBaseUsernameMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_username"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_username CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase.Mealie__schema__user__user__UserBase_username();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.MealieSchemaUserUserUserBaseUsernameMember1 = new global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_usernameMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(MealieSchemaUserUserUserBaseUsernameMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(MealieSchemaUserUserUserBaseUsernameMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Mealie__schema__user__user__UserBase_usernameMember1>(null, MealieSchemaUserUserUserBaseUsernameMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
