// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MealiMCP.Server.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Nutrition : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The calories property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_calories? Calories { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_calories Calories { get; set; }
#endif
        /// <summary>The carbohydrateContent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_carbohydrateContent? CarbohydrateContent { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_carbohydrateContent CarbohydrateContent { get; set; }
#endif
        /// <summary>The cholesterolContent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_cholesterolContent? CholesterolContent { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_cholesterolContent CholesterolContent { get; set; }
#endif
        /// <summary>The fatContent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_fatContent? FatContent { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_fatContent FatContent { get; set; }
#endif
        /// <summary>The fiberContent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_fiberContent? FiberContent { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_fiberContent FiberContent { get; set; }
#endif
        /// <summary>The proteinContent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_proteinContent? ProteinContent { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_proteinContent ProteinContent { get; set; }
#endif
        /// <summary>The saturatedFatContent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_saturatedFatContent? SaturatedFatContent { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_saturatedFatContent SaturatedFatContent { get; set; }
#endif
        /// <summary>The sodiumContent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_sodiumContent? SodiumContent { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_sodiumContent SodiumContent { get; set; }
#endif
        /// <summary>The sugarContent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_sugarContent? SugarContent { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_sugarContent SugarContent { get; set; }
#endif
        /// <summary>The transFatContent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_transFatContent? TransFatContent { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_transFatContent TransFatContent { get; set; }
#endif
        /// <summary>The unsaturatedFatContent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_unsaturatedFatContent? UnsaturatedFatContent { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_unsaturatedFatContent UnsaturatedFatContent { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Models.Nutrition"/> and sets the default values.
        /// </summary>
        public Nutrition()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.Nutrition"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MealiMCP.Server.Api.Models.Nutrition CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MealiMCP.Server.Api.Models.Nutrition();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "calories", n => { Calories = n.GetObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_calories>(global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_calories.CreateFromDiscriminatorValue); } },
                { "carbohydrateContent", n => { CarbohydrateContent = n.GetObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_carbohydrateContent>(global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_carbohydrateContent.CreateFromDiscriminatorValue); } },
                { "cholesterolContent", n => { CholesterolContent = n.GetObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_cholesterolContent>(global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_cholesterolContent.CreateFromDiscriminatorValue); } },
                { "fatContent", n => { FatContent = n.GetObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_fatContent>(global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_fatContent.CreateFromDiscriminatorValue); } },
                { "fiberContent", n => { FiberContent = n.GetObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_fiberContent>(global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_fiberContent.CreateFromDiscriminatorValue); } },
                { "proteinContent", n => { ProteinContent = n.GetObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_proteinContent>(global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_proteinContent.CreateFromDiscriminatorValue); } },
                { "saturatedFatContent", n => { SaturatedFatContent = n.GetObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_saturatedFatContent>(global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_saturatedFatContent.CreateFromDiscriminatorValue); } },
                { "sodiumContent", n => { SodiumContent = n.GetObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_sodiumContent>(global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_sodiumContent.CreateFromDiscriminatorValue); } },
                { "sugarContent", n => { SugarContent = n.GetObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_sugarContent>(global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_sugarContent.CreateFromDiscriminatorValue); } },
                { "transFatContent", n => { TransFatContent = n.GetObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_transFatContent>(global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_transFatContent.CreateFromDiscriminatorValue); } },
                { "unsaturatedFatContent", n => { UnsaturatedFatContent = n.GetObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_unsaturatedFatContent>(global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_unsaturatedFatContent.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_calories>("calories", Calories);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_carbohydrateContent>("carbohydrateContent", CarbohydrateContent);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_cholesterolContent>("cholesterolContent", CholesterolContent);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_fatContent>("fatContent", FatContent);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_fiberContent>("fiberContent", FiberContent);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_proteinContent>("proteinContent", ProteinContent);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_saturatedFatContent>("saturatedFatContent", SaturatedFatContent);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_sodiumContent>("sodiumContent", SodiumContent);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_sugarContent>("sugarContent", SugarContent);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_transFatContent>("transFatContent", TransFatContent);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_unsaturatedFatContent>("unsaturatedFatContent", UnsaturatedFatContent);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.Nutrition_caloriesMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Nutrition_calories : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.Nutrition_caloriesMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.Nutrition_caloriesMember1? NutritionCaloriesMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.Nutrition_caloriesMember1 NutritionCaloriesMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_calories"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_calories CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_calories();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.NutritionCaloriesMember1 = new global::MealiMCP.Server.Api.Models.Nutrition_caloriesMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(NutritionCaloriesMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(NutritionCaloriesMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition_caloriesMember1>(null, NutritionCaloriesMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.Nutrition_carbohydrateContentMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Nutrition_carbohydrateContent : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.Nutrition_carbohydrateContentMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.Nutrition_carbohydrateContentMember1? NutritionCarbohydrateContentMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.Nutrition_carbohydrateContentMember1 NutritionCarbohydrateContentMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_carbohydrateContent"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_carbohydrateContent CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_carbohydrateContent();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.NutritionCarbohydrateContentMember1 = new global::MealiMCP.Server.Api.Models.Nutrition_carbohydrateContentMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(NutritionCarbohydrateContentMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(NutritionCarbohydrateContentMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition_carbohydrateContentMember1>(null, NutritionCarbohydrateContentMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.Nutrition_cholesterolContentMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Nutrition_cholesterolContent : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.Nutrition_cholesterolContentMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.Nutrition_cholesterolContentMember1? NutritionCholesterolContentMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.Nutrition_cholesterolContentMember1 NutritionCholesterolContentMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_cholesterolContent"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_cholesterolContent CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_cholesterolContent();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.NutritionCholesterolContentMember1 = new global::MealiMCP.Server.Api.Models.Nutrition_cholesterolContentMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(NutritionCholesterolContentMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(NutritionCholesterolContentMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition_cholesterolContentMember1>(null, NutritionCholesterolContentMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.Nutrition_fatContentMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Nutrition_fatContent : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.Nutrition_fatContentMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.Nutrition_fatContentMember1? NutritionFatContentMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.Nutrition_fatContentMember1 NutritionFatContentMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_fatContent"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_fatContent CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_fatContent();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.NutritionFatContentMember1 = new global::MealiMCP.Server.Api.Models.Nutrition_fatContentMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(NutritionFatContentMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(NutritionFatContentMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition_fatContentMember1>(null, NutritionFatContentMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.Nutrition_fiberContentMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Nutrition_fiberContent : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.Nutrition_fiberContentMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.Nutrition_fiberContentMember1? NutritionFiberContentMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.Nutrition_fiberContentMember1 NutritionFiberContentMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_fiberContent"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_fiberContent CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_fiberContent();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.NutritionFiberContentMember1 = new global::MealiMCP.Server.Api.Models.Nutrition_fiberContentMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(NutritionFiberContentMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(NutritionFiberContentMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition_fiberContentMember1>(null, NutritionFiberContentMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.Nutrition_proteinContentMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Nutrition_proteinContent : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.Nutrition_proteinContentMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.Nutrition_proteinContentMember1? NutritionProteinContentMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.Nutrition_proteinContentMember1 NutritionProteinContentMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_proteinContent"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_proteinContent CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_proteinContent();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.NutritionProteinContentMember1 = new global::MealiMCP.Server.Api.Models.Nutrition_proteinContentMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(NutritionProteinContentMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(NutritionProteinContentMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition_proteinContentMember1>(null, NutritionProteinContentMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.Nutrition_saturatedFatContentMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Nutrition_saturatedFatContent : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.Nutrition_saturatedFatContentMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.Nutrition_saturatedFatContentMember1? NutritionSaturatedFatContentMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.Nutrition_saturatedFatContentMember1 NutritionSaturatedFatContentMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_saturatedFatContent"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_saturatedFatContent CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_saturatedFatContent();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.NutritionSaturatedFatContentMember1 = new global::MealiMCP.Server.Api.Models.Nutrition_saturatedFatContentMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(NutritionSaturatedFatContentMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(NutritionSaturatedFatContentMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition_saturatedFatContentMember1>(null, NutritionSaturatedFatContentMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.Nutrition_sodiumContentMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Nutrition_sodiumContent : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.Nutrition_sodiumContentMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.Nutrition_sodiumContentMember1? NutritionSodiumContentMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.Nutrition_sodiumContentMember1 NutritionSodiumContentMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_sodiumContent"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_sodiumContent CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_sodiumContent();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.NutritionSodiumContentMember1 = new global::MealiMCP.Server.Api.Models.Nutrition_sodiumContentMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(NutritionSodiumContentMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(NutritionSodiumContentMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition_sodiumContentMember1>(null, NutritionSodiumContentMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.Nutrition_sugarContentMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Nutrition_sugarContent : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.Nutrition_sugarContentMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.Nutrition_sugarContentMember1? NutritionSugarContentMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.Nutrition_sugarContentMember1 NutritionSugarContentMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_sugarContent"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_sugarContent CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_sugarContent();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.NutritionSugarContentMember1 = new global::MealiMCP.Server.Api.Models.Nutrition_sugarContentMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(NutritionSugarContentMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(NutritionSugarContentMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition_sugarContentMember1>(null, NutritionSugarContentMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.Nutrition_transFatContentMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Nutrition_transFatContent : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.Nutrition_transFatContentMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.Nutrition_transFatContentMember1? NutritionTransFatContentMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.Nutrition_transFatContentMember1 NutritionTransFatContentMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_transFatContent"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_transFatContent CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_transFatContent();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.NutritionTransFatContentMember1 = new global::MealiMCP.Server.Api.Models.Nutrition_transFatContentMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(NutritionTransFatContentMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(NutritionTransFatContentMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition_transFatContentMember1>(null, NutritionTransFatContentMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.Nutrition_unsaturatedFatContentMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Nutrition_unsaturatedFatContent : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.Nutrition_unsaturatedFatContentMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.Nutrition_unsaturatedFatContentMember1? NutritionUnsaturatedFatContentMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.Nutrition_unsaturatedFatContentMember1 NutritionUnsaturatedFatContentMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_unsaturatedFatContent"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_unsaturatedFatContent CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.Nutrition.Nutrition_unsaturatedFatContent();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.NutritionUnsaturatedFatContentMember1 = new global::MealiMCP.Server.Api.Models.Nutrition_unsaturatedFatContentMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(NutritionUnsaturatedFatContentMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(NutritionUnsaturatedFatContentMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.Nutrition_unsaturatedFatContentMember1>(null, NutritionUnsaturatedFatContentMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
