// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MealiMCP.Server.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaginationBase_UserSummary_ : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MealiMCP.Server.Api.Models.UserSummary>? Items { get; set; }
#nullable restore
#else
        public List<global::MealiMCP.Server.Api.Models.UserSummary> Items { get; set; }
#endif
        /// <summary>The next property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_.PaginationBase_UserSummary__next? Next { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_.PaginationBase_UserSummary__next Next { get; set; }
#endif
        /// <summary>The page property</summary>
        public int? Page { get; set; }
        /// <summary>The per_page property</summary>
        public int? PerPage { get; set; }
        /// <summary>The previous property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_.PaginationBase_UserSummary__previous? Previous { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_.PaginationBase_UserSummary__previous Previous { get; set; }
#endif
        /// <summary>The total property</summary>
        public int? Total { get; set; }
        /// <summary>The total_pages property</summary>
        public int? TotalPages { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_"/> and sets the default values.
        /// </summary>
        public PaginationBase_UserSummary_()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_ CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::MealiMCP.Server.Api.Models.UserSummary>(global::MealiMCP.Server.Api.Models.UserSummary.CreateFromDiscriminatorValue)?.AsList(); } },
                { "next", n => { Next = n.GetObjectValue<global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_.PaginationBase_UserSummary__next>(global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_.PaginationBase_UserSummary__next.CreateFromDiscriminatorValue); } },
                { "page", n => { Page = n.GetIntValue(); } },
                { "per_page", n => { PerPage = n.GetIntValue(); } },
                { "previous", n => { Previous = n.GetObjectValue<global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_.PaginationBase_UserSummary__previous>(global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_.PaginationBase_UserSummary__previous.CreateFromDiscriminatorValue); } },
                { "total", n => { Total = n.GetIntValue(); } },
                { "total_pages", n => { TotalPages = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::MealiMCP.Server.Api.Models.UserSummary>("items", Items);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_.PaginationBase_UserSummary__next>("next", Next);
            writer.WriteIntValue("page", Page);
            writer.WriteIntValue("per_page", PerPage);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_.PaginationBase_UserSummary__previous>("previous", Previous);
            writer.WriteIntValue("total", Total);
            writer.WriteIntValue("total_pages", TotalPages);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary__nextMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PaginationBase_UserSummary__next : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary__nextMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary__nextMember1? PaginationBaseUserSummaryNextMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary__nextMember1 PaginationBaseUserSummaryNextMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_.PaginationBase_UserSummary__next"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_.PaginationBase_UserSummary__next CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_.PaginationBase_UserSummary__next();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.PaginationBaseUserSummaryNextMember1 = new global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary__nextMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(PaginationBaseUserSummaryNextMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(PaginationBaseUserSummaryNextMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary__nextMember1>(null, PaginationBaseUserSummaryNextMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary__previousMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class PaginationBase_UserSummary__previous : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary__previousMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary__previousMember1? PaginationBaseUserSummaryPreviousMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary__previousMember1 PaginationBaseUserSummaryPreviousMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_.PaginationBase_UserSummary__previous"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_.PaginationBase_UserSummary__previous CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary_.PaginationBase_UserSummary__previous();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.PaginationBaseUserSummaryPreviousMember1 = new global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary__previousMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(PaginationBaseUserSummaryPreviousMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(PaginationBaseUserSummaryPreviousMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.PaginationBase_UserSummary__previousMember1>(null, PaginationBaseUserSummaryPreviousMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
