// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MealiMCP.Server.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class QueryFilterJSONPart : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attributeName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_attributeName? AttributeName { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_attributeName AttributeName { get; set; }
#endif
        /// <summary>The leftParenthesis property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_leftParenthesis? LeftParenthesis { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_leftParenthesis LeftParenthesis { get; set; }
#endif
        /// <summary>The logicalOperator property</summary>
        public global::MealiMCP.Server.Api.Models.LogicalOperator? LogicalOperator { get; set; }
        /// <summary>The relationalOperator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_relationalOperator? RelationalOperator { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_relationalOperator RelationalOperator { get; set; }
#endif
        /// <summary>The rightParenthesis property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_rightParenthesis? RightParenthesis { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_rightParenthesis RightParenthesis { get; set; }
#endif
        /// <summary>The value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_value? Value { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_value Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Models.QueryFilterJSONPart"/> and sets the default values.
        /// </summary>
        public QueryFilterJSONPart()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.QueryFilterJSONPart"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MealiMCP.Server.Api.Models.QueryFilterJSONPart CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MealiMCP.Server.Api.Models.QueryFilterJSONPart();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attributeName", n => { AttributeName = n.GetObjectValue<global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_attributeName>(global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_attributeName.CreateFromDiscriminatorValue); } },
                { "leftParenthesis", n => { LeftParenthesis = n.GetObjectValue<global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_leftParenthesis>(global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_leftParenthesis.CreateFromDiscriminatorValue); } },
                { "logicalOperator", n => { LogicalOperator = n.GetEnumValue<global::MealiMCP.Server.Api.Models.LogicalOperator>(); } },
                { "relationalOperator", n => { RelationalOperator = n.GetObjectValue<global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_relationalOperator>(global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_relationalOperator.CreateFromDiscriminatorValue); } },
                { "rightParenthesis", n => { RightParenthesis = n.GetObjectValue<global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_rightParenthesis>(global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_rightParenthesis.CreateFromDiscriminatorValue); } },
                { "value", n => { Value = n.GetObjectValue<global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_value>(global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_value.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_attributeName>("attributeName", AttributeName);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_leftParenthesis>("leftParenthesis", LeftParenthesis);
            writer.WriteEnumValue<global::MealiMCP.Server.Api.Models.LogicalOperator>("logicalOperator", LogicalOperator);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_relationalOperator>("relationalOperator", RelationalOperator);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_rightParenthesis>("rightParenthesis", RightParenthesis);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_value>("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_attributeNameMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class QueryFilterJSONPart_attributeName : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_attributeNameMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_attributeNameMember1? QueryFilterJSONPartAttributeNameMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_attributeNameMember1 QueryFilterJSONPartAttributeNameMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_attributeName"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_attributeName CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_attributeName();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.QueryFilterJSONPartAttributeNameMember1 = new global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_attributeNameMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(QueryFilterJSONPartAttributeNameMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(QueryFilterJSONPartAttributeNameMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_attributeNameMember1>(null, QueryFilterJSONPartAttributeNameMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_leftParenthesisMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class QueryFilterJSONPart_leftParenthesis : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_leftParenthesisMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_leftParenthesisMember1? QueryFilterJSONPartLeftParenthesisMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_leftParenthesisMember1 QueryFilterJSONPartLeftParenthesisMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_leftParenthesis"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_leftParenthesis CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_leftParenthesis();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.QueryFilterJSONPartLeftParenthesisMember1 = new global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_leftParenthesisMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(QueryFilterJSONPartLeftParenthesisMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(QueryFilterJSONPartLeftParenthesisMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_leftParenthesisMember1>(null, QueryFilterJSONPartLeftParenthesisMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_relationalOperatorMember1"/>, <see cref="global::MealiMCP.Server.Api.Models.RelationalKeyword"/>, <see cref="global::MealiMCP.Server.Api.Models.RelationalOperator"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class QueryFilterJSONPart_relationalOperator : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_relationalOperatorMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_relationalOperatorMember1? QueryFilterJSONPartRelationalOperatorMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_relationalOperatorMember1 QueryFilterJSONPartRelationalOperatorMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.RelationalKeyword"/></summary>
            public global::MealiMCP.Server.Api.Models.RelationalKeyword? RelationalKeyword { get; set; }
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.RelationalOperator"/></summary>
            public global::MealiMCP.Server.Api.Models.RelationalOperator? RelationalOperator { get; set; }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_relationalOperator"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_relationalOperator CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_relationalOperator();
                if(parseNode.GetEnumValue<global::MealiMCP.Server.Api.Models.RelationalKeyword>() is global::MealiMCP.Server.Api.Models.RelationalKeyword relationalKeywordValue)
                {
                    result.RelationalKeyword = relationalKeywordValue;
                }
                else if(parseNode.GetEnumValue<global::MealiMCP.Server.Api.Models.RelationalOperator>() is global::MealiMCP.Server.Api.Models.RelationalOperator relationalOperatorValue)
                {
                    result.RelationalOperator = relationalOperatorValue;
                }
                else {
                    result.QueryFilterJSONPartRelationalOperatorMember1 = new global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_relationalOperatorMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(QueryFilterJSONPartRelationalOperatorMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(QueryFilterJSONPartRelationalOperatorMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(RelationalKeyword != null)
                {
                    writer.WriteEnumValue<global::MealiMCP.Server.Api.Models.RelationalKeyword>(null, RelationalKeyword);
                }
                else if(RelationalOperator != null)
                {
                    writer.WriteEnumValue<global::MealiMCP.Server.Api.Models.RelationalOperator>(null, RelationalOperator);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_relationalOperatorMember1>(null, QueryFilterJSONPartRelationalOperatorMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_rightParenthesisMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class QueryFilterJSONPart_rightParenthesis : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_rightParenthesisMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_rightParenthesisMember1? QueryFilterJSONPartRightParenthesisMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_rightParenthesisMember1 QueryFilterJSONPartRightParenthesisMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_rightParenthesis"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_rightParenthesis CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_rightParenthesis();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.QueryFilterJSONPartRightParenthesisMember1 = new global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_rightParenthesisMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(QueryFilterJSONPartRightParenthesisMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(QueryFilterJSONPartRightParenthesisMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_rightParenthesisMember1>(null, QueryFilterJSONPartRightParenthesisMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_valueMember1"/>, <see cref="string"/>, List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class QueryFilterJSONPart_value : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_valueMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_valueMember1? QueryFilterJSONPartValueMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_valueMember1 QueryFilterJSONPartValueMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? QueryFilterJSONPartValueString { get; set; }
#nullable restore
#else
            public string QueryFilterJSONPartValueString { get; set; }
#endif
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_value"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_value CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.QueryFilterJSONPart.QueryFilterJSONPart_value();
                if(parseNode.GetStringValue() is string queryFilterJSONPartValueStringValue)
                {
                    result.QueryFilterJSONPartValueString = queryFilterJSONPartValueStringValue;
                }
                else if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.QueryFilterJSONPartValueMember1 = new global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_valueMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(QueryFilterJSONPartValueMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(QueryFilterJSONPartValueMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(QueryFilterJSONPartValueString != null)
                {
                    writer.WriteStringValue(null, QueryFilterJSONPartValueString);
                }
                else if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.QueryFilterJSONPart_valueMember1>(null, QueryFilterJSONPartValueMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
