// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MealiMCP.Server.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RecipeSettings : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The disableComments property</summary>
        public bool? DisableComments { get; set; }
        /// <summary>The landscapeView property</summary>
        public bool? LandscapeView { get; set; }
        /// <summary>The locked property</summary>
        public bool? Locked { get; set; }
        /// <summary>The public property</summary>
        public bool? Public { get; set; }
        /// <summary>The showAssets property</summary>
        public bool? ShowAssets { get; set; }
        /// <summary>The showNutrition property</summary>
        public bool? ShowNutrition { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Models.RecipeSettings"/> and sets the default values.
        /// </summary>
        public RecipeSettings()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.RecipeSettings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MealiMCP.Server.Api.Models.RecipeSettings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MealiMCP.Server.Api.Models.RecipeSettings();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "disableComments", n => { DisableComments = n.GetBoolValue(); } },
                { "landscapeView", n => { LandscapeView = n.GetBoolValue(); } },
                { "locked", n => { Locked = n.GetBoolValue(); } },
                { "public", n => { Public = n.GetBoolValue(); } },
                { "showAssets", n => { ShowAssets = n.GetBoolValue(); } },
                { "showNutrition", n => { ShowNutrition = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("disableComments", DisableComments);
            writer.WriteBoolValue("landscapeView", LandscapeView);
            writer.WriteBoolValue("locked", Locked);
            writer.WriteBoolValue("public", Public);
            writer.WriteBoolValue("showAssets", ShowAssets);
            writer.WriteBoolValue("showNutrition", ShowNutrition);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
