// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MealiMCP.Server.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RecipeTimelineEventOut : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The eventMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.RecipeTimelineEventOut.RecipeTimelineEventOut_eventMessage? EventMessage { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.RecipeTimelineEventOut.RecipeTimelineEventOut_eventMessage EventMessage { get; set; }
#endif
        /// <summary>The eventType property</summary>
        public global::MealiMCP.Server.Api.Models.TimelineEventType? EventType { get; set; }
        /// <summary>The groupId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupId { get; set; }
#nullable restore
#else
        public string GroupId { get; set; }
#endif
        /// <summary>The householdId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HouseholdId { get; set; }
#nullable restore
#else
        public string HouseholdId { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The image property</summary>
        public global::MealiMCP.Server.Api.Models.TimelineEventImage? Image { get; set; }
        /// <summary>The recipeId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecipeId { get; set; }
#nullable restore
#else
        public string RecipeId { get; set; }
#endif
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>The timestamp property</summary>
        public DateTimeOffset? Timestamp { get; set; }
        /// <summary>The updatedAt property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The userId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Models.RecipeTimelineEventOut"/> and sets the default values.
        /// </summary>
        public RecipeTimelineEventOut()
        {
            AdditionalData = new Dictionary<string, object>();
            Image = global::MealiMCP.Server.Api.Models.TimelineEventImage.DoesNotHaveImage;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.RecipeTimelineEventOut"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MealiMCP.Server.Api.Models.RecipeTimelineEventOut CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MealiMCP.Server.Api.Models.RecipeTimelineEventOut();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "eventMessage", n => { EventMessage = n.GetObjectValue<global::MealiMCP.Server.Api.Models.RecipeTimelineEventOut.RecipeTimelineEventOut_eventMessage>(global::MealiMCP.Server.Api.Models.RecipeTimelineEventOut.RecipeTimelineEventOut_eventMessage.CreateFromDiscriminatorValue); } },
                { "eventType", n => { EventType = n.GetEnumValue<global::MealiMCP.Server.Api.Models.TimelineEventType>(); } },
                { "groupId", n => { GroupId = n.GetStringValue(); } },
                { "householdId", n => { HouseholdId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "image", n => { Image = n.GetEnumValue<global::MealiMCP.Server.Api.Models.TimelineEventImage>(); } },
                { "recipeId", n => { RecipeId = n.GetStringValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "timestamp", n => { Timestamp = n.GetDateTimeOffsetValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "userId", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.RecipeTimelineEventOut.RecipeTimelineEventOut_eventMessage>("eventMessage", EventMessage);
            writer.WriteEnumValue<global::MealiMCP.Server.Api.Models.TimelineEventType>("eventType", EventType);
            writer.WriteStringValue("groupId", GroupId);
            writer.WriteStringValue("householdId", HouseholdId);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::MealiMCP.Server.Api.Models.TimelineEventImage>("image", Image);
            writer.WriteStringValue("recipeId", RecipeId);
            writer.WriteStringValue("subject", Subject);
            writer.WriteDateTimeOffsetValue("timestamp", Timestamp);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteStringValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.RecipeTimelineEventOut_eventMessageMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RecipeTimelineEventOut_eventMessage : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.RecipeTimelineEventOut_eventMessageMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.RecipeTimelineEventOut_eventMessageMember1? RecipeTimelineEventOutEventMessageMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.RecipeTimelineEventOut_eventMessageMember1 RecipeTimelineEventOutEventMessageMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.RecipeTimelineEventOut.RecipeTimelineEventOut_eventMessage"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.RecipeTimelineEventOut.RecipeTimelineEventOut_eventMessage CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.RecipeTimelineEventOut.RecipeTimelineEventOut_eventMessage();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.RecipeTimelineEventOutEventMessageMember1 = new global::MealiMCP.Server.Api.Models.RecipeTimelineEventOut_eventMessageMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(RecipeTimelineEventOutEventMessageMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(RecipeTimelineEventOutEventMessageMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.RecipeTimelineEventOut_eventMessageMember1>(null, RecipeTimelineEventOutEventMessageMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
