// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MealiMCP.Server.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RecipeTimelineEventUpdate : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The eventMessage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.RecipeTimelineEventUpdate.RecipeTimelineEventUpdate_eventMessage? EventMessage { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.RecipeTimelineEventUpdate.RecipeTimelineEventUpdate_eventMessage EventMessage { get; set; }
#endif
        /// <summary>The image property</summary>
        public global::MealiMCP.Server.Api.Models.TimelineEventImage? Image { get; set; }
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Models.RecipeTimelineEventUpdate"/> and sets the default values.
        /// </summary>
        public RecipeTimelineEventUpdate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.RecipeTimelineEventUpdate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MealiMCP.Server.Api.Models.RecipeTimelineEventUpdate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MealiMCP.Server.Api.Models.RecipeTimelineEventUpdate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "eventMessage", n => { EventMessage = n.GetObjectValue<global::MealiMCP.Server.Api.Models.RecipeTimelineEventUpdate.RecipeTimelineEventUpdate_eventMessage>(global::MealiMCP.Server.Api.Models.RecipeTimelineEventUpdate.RecipeTimelineEventUpdate_eventMessage.CreateFromDiscriminatorValue); } },
                { "image", n => { Image = n.GetEnumValue<global::MealiMCP.Server.Api.Models.TimelineEventImage>(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.RecipeTimelineEventUpdate.RecipeTimelineEventUpdate_eventMessage>("eventMessage", EventMessage);
            writer.WriteEnumValue<global::MealiMCP.Server.Api.Models.TimelineEventImage>("image", Image);
            writer.WriteStringValue("subject", Subject);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.RecipeTimelineEventUpdate_eventMessageMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RecipeTimelineEventUpdate_eventMessage : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.RecipeTimelineEventUpdate_eventMessageMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.RecipeTimelineEventUpdate_eventMessageMember1? RecipeTimelineEventUpdateEventMessageMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.RecipeTimelineEventUpdate_eventMessageMember1 RecipeTimelineEventUpdateEventMessageMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.RecipeTimelineEventUpdate.RecipeTimelineEventUpdate_eventMessage"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.RecipeTimelineEventUpdate.RecipeTimelineEventUpdate_eventMessage CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.RecipeTimelineEventUpdate.RecipeTimelineEventUpdate_eventMessage();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.RecipeTimelineEventUpdateEventMessageMember1 = new global::MealiMCP.Server.Api.Models.RecipeTimelineEventUpdate_eventMessageMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(RecipeTimelineEventUpdateEventMessageMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(RecipeTimelineEventUpdateEventMessageMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.RecipeTimelineEventUpdate_eventMessageMember1>(null, RecipeTimelineEventUpdateEventMessageMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
