// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MealiMCP.Server.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ShoppingListItemCreate : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The checked property</summary>
        public bool? Checked { get; set; }
        /// <summary>The display property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Display { get; set; }
#nullable restore
#else
        public string Display { get; set; }
#endif
        /// <summary>The extras property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Extras { get; set; }
#nullable restore
#else
        public UntypedNode Extras { get; set; }
#endif
        /// <summary>The food property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_food? Food { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_food Food { get; set; }
#endif
        /// <summary>The foodId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_foodId? FoodId { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_foodId FoodId { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_id? Id { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_id Id { get; set; }
#endif
        /// <summary>The labelId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_labelId? LabelId { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_labelId LabelId { get; set; }
#endif
        /// <summary>The note property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_note? Note { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_note Note { get; set; }
#endif
        /// <summary>The position property</summary>
        public int? Position { get; set; }
        /// <summary>The quantity property</summary>
        public double? Quantity { get; set; }
        /// <summary>The recipeReferences property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MealiMCP.Server.Api.Models.ShoppingListItemRecipeRefCreate>? RecipeReferences { get; set; }
#nullable restore
#else
        public List<global::MealiMCP.Server.Api.Models.ShoppingListItemRecipeRefCreate> RecipeReferences { get; set; }
#endif
        /// <summary>The referencedRecipe property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.RecipeInput? ReferencedRecipe { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.RecipeInput ReferencedRecipe { get; set; }
#endif
        /// <summary>The shoppingListId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShoppingListId { get; set; }
#nullable restore
#else
        public string ShoppingListId { get; set; }
#endif
        /// <summary>The unit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_unit? Unit { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_unit Unit { get; set; }
#endif
        /// <summary>The unitId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_unitId? UnitId { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_unitId UnitId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate"/> and sets the default values.
        /// </summary>
        public ShoppingListItemCreate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MealiMCP.Server.Api.Models.ShoppingListItemCreate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MealiMCP.Server.Api.Models.ShoppingListItemCreate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "checked", n => { Checked = n.GetBoolValue(); } },
                { "display", n => { Display = n.GetStringValue(); } },
                { "extras", n => { Extras = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "food", n => { Food = n.GetObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_food>(global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_food.CreateFromDiscriminatorValue); } },
                { "foodId", n => { FoodId = n.GetObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_foodId>(global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_foodId.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_id>(global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_id.CreateFromDiscriminatorValue); } },
                { "labelId", n => { LabelId = n.GetObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_labelId>(global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_labelId.CreateFromDiscriminatorValue); } },
                { "note", n => { Note = n.GetObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_note>(global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_note.CreateFromDiscriminatorValue); } },
                { "position", n => { Position = n.GetIntValue(); } },
                { "quantity", n => { Quantity = n.GetDoubleValue(); } },
                { "recipeReferences", n => { RecipeReferences = n.GetCollectionOfObjectValues<global::MealiMCP.Server.Api.Models.ShoppingListItemRecipeRefCreate>(global::MealiMCP.Server.Api.Models.ShoppingListItemRecipeRefCreate.CreateFromDiscriminatorValue)?.AsList(); } },
                { "referencedRecipe", n => { ReferencedRecipe = n.GetObjectValue<global::MealiMCP.Server.Api.Models.RecipeInput>(global::MealiMCP.Server.Api.Models.RecipeInput.CreateFromDiscriminatorValue); } },
                { "shoppingListId", n => { ShoppingListId = n.GetStringValue(); } },
                { "unit", n => { Unit = n.GetObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_unit>(global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_unit.CreateFromDiscriminatorValue); } },
                { "unitId", n => { UnitId = n.GetObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_unitId>(global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_unitId.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("checked", Checked);
            writer.WriteStringValue("display", Display);
            writer.WriteObjectValue<UntypedNode>("extras", Extras);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_food>("food", Food);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_foodId>("foodId", FoodId);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_id>("id", Id);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_labelId>("labelId", LabelId);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_note>("note", Note);
            writer.WriteIntValue("position", Position);
            writer.WriteDoubleValue("quantity", Quantity);
            writer.WriteCollectionOfObjectValues<global::MealiMCP.Server.Api.Models.ShoppingListItemRecipeRefCreate>("recipeReferences", RecipeReferences);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.RecipeInput>("referencedRecipe", ReferencedRecipe);
            writer.WriteStringValue("shoppingListId", ShoppingListId);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_unit>("unit", Unit);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_unitId>("unitId", UnitId);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.CreateIngredientFood"/>, <see cref="global::MealiMCP.Server.Api.Models.IngredientFoodInput"/>, <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_foodMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemCreate_food : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.CreateIngredientFood"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.CreateIngredientFood? CreateIngredientFood { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.CreateIngredientFood CreateIngredientFood { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.IngredientFoodInput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.IngredientFoodInput? IngredientFoodInput { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.IngredientFoodInput IngredientFoodInput { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_foodMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_foodMember1? ShoppingListItemCreateFoodMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_foodMember1 ShoppingListItemCreateFoodMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_food"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_food CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_food();
                result.CreateIngredientFood = new global::MealiMCP.Server.Api.Models.CreateIngredientFood();
                result.IngredientFoodInput = new global::MealiMCP.Server.Api.Models.IngredientFoodInput();
                result.ShoppingListItemCreateFoodMember1 = new global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_foodMember1();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CreateIngredientFood != null || IngredientFoodInput != null || ShoppingListItemCreateFoodMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CreateIngredientFood, IngredientFoodInput, ShoppingListItemCreateFoodMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.CreateIngredientFood>(null, CreateIngredientFood, IngredientFoodInput, ShoppingListItemCreateFoodMember1);
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_foodIdMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemCreate_foodId : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_foodIdMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_foodIdMember1? ShoppingListItemCreateFoodIdMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_foodIdMember1 ShoppingListItemCreateFoodIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_foodId"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_foodId CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_foodId();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ShoppingListItemCreateFoodIdMember1 = new global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_foodIdMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ShoppingListItemCreateFoodIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ShoppingListItemCreateFoodIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_foodIdMember1>(null, ShoppingListItemCreateFoodIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_idMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemCreate_id : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_idMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_idMember1? ShoppingListItemCreateIdMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_idMember1 ShoppingListItemCreateIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_id"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_id CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_id();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ShoppingListItemCreateIdMember1 = new global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_idMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ShoppingListItemCreateIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ShoppingListItemCreateIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_idMember1>(null, ShoppingListItemCreateIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_labelIdMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemCreate_labelId : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_labelIdMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_labelIdMember1? ShoppingListItemCreateLabelIdMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_labelIdMember1 ShoppingListItemCreateLabelIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_labelId"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_labelId CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_labelId();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ShoppingListItemCreateLabelIdMember1 = new global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_labelIdMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ShoppingListItemCreateLabelIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ShoppingListItemCreateLabelIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_labelIdMember1>(null, ShoppingListItemCreateLabelIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_noteMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemCreate_note : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_noteMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_noteMember1? ShoppingListItemCreateNoteMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_noteMember1 ShoppingListItemCreateNoteMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_note"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_note CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_note();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ShoppingListItemCreateNoteMember1 = new global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_noteMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ShoppingListItemCreateNoteMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ShoppingListItemCreateNoteMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_noteMember1>(null, ShoppingListItemCreateNoteMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.CreateIngredientUnit"/>, <see cref="global::MealiMCP.Server.Api.Models.IngredientUnitInput"/>, <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_unitMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemCreate_unit : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.CreateIngredientUnit"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.CreateIngredientUnit? CreateIngredientUnit { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.CreateIngredientUnit CreateIngredientUnit { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.IngredientUnitInput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.IngredientUnitInput? IngredientUnitInput { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.IngredientUnitInput IngredientUnitInput { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_unitMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_unitMember1? ShoppingListItemCreateUnitMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_unitMember1 ShoppingListItemCreateUnitMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_unit"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_unit CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_unit();
                result.CreateIngredientUnit = new global::MealiMCP.Server.Api.Models.CreateIngredientUnit();
                result.IngredientUnitInput = new global::MealiMCP.Server.Api.Models.IngredientUnitInput();
                result.ShoppingListItemCreateUnitMember1 = new global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_unitMember1();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CreateIngredientUnit != null || IngredientUnitInput != null || ShoppingListItemCreateUnitMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CreateIngredientUnit, IngredientUnitInput, ShoppingListItemCreateUnitMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.CreateIngredientUnit>(null, CreateIngredientUnit, IngredientUnitInput, ShoppingListItemCreateUnitMember1);
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_unitIdMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemCreate_unitId : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_unitIdMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_unitIdMember1? ShoppingListItemCreateUnitIdMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_unitIdMember1 ShoppingListItemCreateUnitIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_unitId"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_unitId CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.ShoppingListItemCreate.ShoppingListItemCreate_unitId();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ShoppingListItemCreateUnitIdMember1 = new global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_unitIdMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ShoppingListItemCreateUnitIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ShoppingListItemCreateUnitIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemCreate_unitIdMember1>(null, ShoppingListItemCreateUnitIdMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
