// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MealiMCP.Server.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ShoppingListItemOutInput : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The checked property</summary>
        public bool? Checked { get; set; }
        /// <summary>The createdAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_createdAt? CreatedAt { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_createdAt CreatedAt { get; set; }
#endif
        /// <summary>The display property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Display { get; set; }
#nullable restore
#else
        public string Display { get; set; }
#endif
        /// <summary>The extras property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Extras { get; set; }
#nullable restore
#else
        public UntypedNode Extras { get; set; }
#endif
        /// <summary>The food property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.IngredientFoodInput? Food { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.IngredientFoodInput Food { get; set; }
#endif
        /// <summary>The foodId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_foodId? FoodId { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_foodId FoodId { get; set; }
#endif
        /// <summary>The groupId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GroupId { get; set; }
#nullable restore
#else
        public string GroupId { get; set; }
#endif
        /// <summary>The householdId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HouseholdId { get; set; }
#nullable restore
#else
        public string HouseholdId { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.MultiPurposeLabelSummary? Label { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.MultiPurposeLabelSummary Label { get; set; }
#endif
        /// <summary>The labelId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_labelId? LabelId { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_labelId LabelId { get; set; }
#endif
        /// <summary>The note property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_note? Note { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_note Note { get; set; }
#endif
        /// <summary>The position property</summary>
        public int? Position { get; set; }
        /// <summary>The quantity property</summary>
        public double? Quantity { get; set; }
        /// <summary>The recipeReferences property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MealiMCP.Server.Api.Models.ShoppingListItemRecipeRefOut>? RecipeReferences { get; set; }
#nullable restore
#else
        public List<global::MealiMCP.Server.Api.Models.ShoppingListItemRecipeRefOut> RecipeReferences { get; set; }
#endif
        /// <summary>The referencedRecipe property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.RecipeInput? ReferencedRecipe { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.RecipeInput ReferencedRecipe { get; set; }
#endif
        /// <summary>The shoppingListId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShoppingListId { get; set; }
#nullable restore
#else
        public string ShoppingListId { get; set; }
#endif
        /// <summary>The unit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.IngredientUnitInput? Unit { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.IngredientUnitInput Unit { get; set; }
#endif
        /// <summary>The unitId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_unitId? UnitId { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_unitId UnitId { get; set; }
#endif
        /// <summary>The update_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_update_at? UpdateAt { get; set; }
#nullable restore
#else
        public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_update_at UpdateAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput"/> and sets the default values.
        /// </summary>
        public ShoppingListItemOutInput()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "checked", n => { Checked = n.GetBoolValue(); } },
                { "createdAt", n => { CreatedAt = n.GetObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_createdAt>(global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_createdAt.CreateFromDiscriminatorValue); } },
                { "display", n => { Display = n.GetStringValue(); } },
                { "extras", n => { Extras = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "food", n => { Food = n.GetObjectValue<global::MealiMCP.Server.Api.Models.IngredientFoodInput>(global::MealiMCP.Server.Api.Models.IngredientFoodInput.CreateFromDiscriminatorValue); } },
                { "foodId", n => { FoodId = n.GetObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_foodId>(global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_foodId.CreateFromDiscriminatorValue); } },
                { "groupId", n => { GroupId = n.GetStringValue(); } },
                { "householdId", n => { HouseholdId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "label", n => { Label = n.GetObjectValue<global::MealiMCP.Server.Api.Models.MultiPurposeLabelSummary>(global::MealiMCP.Server.Api.Models.MultiPurposeLabelSummary.CreateFromDiscriminatorValue); } },
                { "labelId", n => { LabelId = n.GetObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_labelId>(global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_labelId.CreateFromDiscriminatorValue); } },
                { "note", n => { Note = n.GetObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_note>(global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_note.CreateFromDiscriminatorValue); } },
                { "position", n => { Position = n.GetIntValue(); } },
                { "quantity", n => { Quantity = n.GetDoubleValue(); } },
                { "recipeReferences", n => { RecipeReferences = n.GetCollectionOfObjectValues<global::MealiMCP.Server.Api.Models.ShoppingListItemRecipeRefOut>(global::MealiMCP.Server.Api.Models.ShoppingListItemRecipeRefOut.CreateFromDiscriminatorValue)?.AsList(); } },
                { "referencedRecipe", n => { ReferencedRecipe = n.GetObjectValue<global::MealiMCP.Server.Api.Models.RecipeInput>(global::MealiMCP.Server.Api.Models.RecipeInput.CreateFromDiscriminatorValue); } },
                { "shoppingListId", n => { ShoppingListId = n.GetStringValue(); } },
                { "unit", n => { Unit = n.GetObjectValue<global::MealiMCP.Server.Api.Models.IngredientUnitInput>(global::MealiMCP.Server.Api.Models.IngredientUnitInput.CreateFromDiscriminatorValue); } },
                { "unitId", n => { UnitId = n.GetObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_unitId>(global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_unitId.CreateFromDiscriminatorValue); } },
                { "update_at", n => { UpdateAt = n.GetObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_update_at>(global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_update_at.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("checked", Checked);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_createdAt>("createdAt", CreatedAt);
            writer.WriteStringValue("display", Display);
            writer.WriteObjectValue<UntypedNode>("extras", Extras);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.IngredientFoodInput>("food", Food);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_foodId>("foodId", FoodId);
            writer.WriteStringValue("groupId", GroupId);
            writer.WriteStringValue("householdId", HouseholdId);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.MultiPurposeLabelSummary>("label", Label);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_labelId>("labelId", LabelId);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_note>("note", Note);
            writer.WriteIntValue("position", Position);
            writer.WriteDoubleValue("quantity", Quantity);
            writer.WriteCollectionOfObjectValues<global::MealiMCP.Server.Api.Models.ShoppingListItemRecipeRefOut>("recipeReferences", RecipeReferences);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.RecipeInput>("referencedRecipe", ReferencedRecipe);
            writer.WriteStringValue("shoppingListId", ShoppingListId);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.IngredientUnitInput>("unit", Unit);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_unitId>("unitId", UnitId);
            writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_update_at>("update_at", UpdateAt);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_createdAtMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemOutInput_createdAt : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_createdAtMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_createdAtMember1? ShoppingListItemOutInputCreatedAtMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_createdAtMember1 ShoppingListItemOutInputCreatedAtMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_createdAt"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_createdAt CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_createdAt();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.ShoppingListItemOutInputCreatedAtMember1 = new global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_createdAtMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ShoppingListItemOutInputCreatedAtMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ShoppingListItemOutInputCreatedAtMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_createdAtMember1>(null, ShoppingListItemOutInputCreatedAtMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_foodIdMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemOutInput_foodId : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_foodIdMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_foodIdMember1? ShoppingListItemOutInputFoodIdMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_foodIdMember1 ShoppingListItemOutInputFoodIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_foodId"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_foodId CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_foodId();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ShoppingListItemOutInputFoodIdMember1 = new global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_foodIdMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ShoppingListItemOutInputFoodIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ShoppingListItemOutInputFoodIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_foodIdMember1>(null, ShoppingListItemOutInputFoodIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_labelIdMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemOutInput_labelId : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_labelIdMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_labelIdMember1? ShoppingListItemOutInputLabelIdMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_labelIdMember1 ShoppingListItemOutInputLabelIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_labelId"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_labelId CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_labelId();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ShoppingListItemOutInputLabelIdMember1 = new global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_labelIdMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ShoppingListItemOutInputLabelIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ShoppingListItemOutInputLabelIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_labelIdMember1>(null, ShoppingListItemOutInputLabelIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_noteMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemOutInput_note : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_noteMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_noteMember1? ShoppingListItemOutInputNoteMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_noteMember1 ShoppingListItemOutInputNoteMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_note"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_note CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_note();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ShoppingListItemOutInputNoteMember1 = new global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_noteMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ShoppingListItemOutInputNoteMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ShoppingListItemOutInputNoteMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_noteMember1>(null, ShoppingListItemOutInputNoteMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_unitIdMember1"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemOutInput_unitId : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_unitIdMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_unitIdMember1? ShoppingListItemOutInputUnitIdMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_unitIdMember1 ShoppingListItemOutInputUnitIdMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_unitId"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_unitId CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_unitId();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.ShoppingListItemOutInputUnitIdMember1 = new global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_unitIdMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ShoppingListItemOutInputUnitIdMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ShoppingListItemOutInputUnitIdMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_unitIdMember1>(null, ShoppingListItemOutInputUnitIdMember1);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="DateTimeOffset"/>, <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_update_atMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ShoppingListItemOutInput_update_at : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="DateTimeOffset"/></summary>
            public DateTimeOffset? DateTimeOffset { get; set; }
            /// <summary>Composed type representation for type <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_update_atMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_update_atMember1? ShoppingListItemOutInputUpdateAtMember1 { get; set; }
#nullable restore
#else
            public global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_update_atMember1 ShoppingListItemOutInputUpdateAtMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_update_at"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_update_at CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput.ShoppingListItemOutInput_update_at();
                if(parseNode.GetDateTimeOffsetValue() is DateTimeOffset dateTimeOffsetValue)
                {
                    result.DateTimeOffset = dateTimeOffsetValue;
                }
                else {
                    result.ShoppingListItemOutInputUpdateAtMember1 = new global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_update_atMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ShoppingListItemOutInputUpdateAtMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ShoppingListItemOutInputUpdateAtMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(DateTimeOffset != null)
                {
                    writer.WriteDateTimeOffsetValue(null, DateTimeOffset);
                }
                else {
                    writer.WriteObjectValue<global::MealiMCP.Server.Api.Models.ShoppingListItemOutInput_update_atMember1>(null, ShoppingListItemOutInputUpdateAtMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
