// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MealiMCP.Server.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum TimelineEventImage
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "has image")]
        #pragma warning disable CS1591
        HasImage,
        #pragma warning restore CS1591
        [EnumMember(Value = "does not have image")]
        #pragma warning disable CS1591
        DoesNotHaveImage,
        #pragma warning restore CS1591
    }
}
