// <auto-generated/>
#pragma warning disable CS0618
using MealiMCP.Server.Api.Api.Explore.Groups.Item.Cookbooks;
using MealiMCP.Server.Api.Api.Explore.Groups.Item.Foods;
using MealiMCP.Server.Api.Api.Explore.Groups.Item.Households;
using MealiMCP.Server.Api.Api.Explore.Groups.Item.Organizers;
using MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MealiMCP.Server.Api.Api.Explore.Groups.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\explore\groups\{group_slug}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithGroup_slugItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The cookbooks property</summary>
        public global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Cookbooks.CookbooksRequestBuilder Cookbooks
        {
            get => new global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Cookbooks.CookbooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The foods property</summary>
        public global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Foods.FoodsRequestBuilder Foods
        {
            get => new global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Foods.FoodsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The households property</summary>
        public global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Households.HouseholdsRequestBuilder Households
        {
            get => new global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Households.HouseholdsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The organizers property</summary>
        public global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Organizers.OrganizersRequestBuilder Organizers
        {
            get => new global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Organizers.OrganizersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recipes property</summary>
        public global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.RecipesRequestBuilder Recipes
        {
            get => new global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.RecipesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Explore.Groups.Item.WithGroup_slugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithGroup_slugItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/explore/groups/{group_slug}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Explore.Groups.Item.WithGroup_slugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithGroup_slugItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/explore/groups/{group_slug}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
