// <auto-generated/>
#pragma warning disable CS0618
using MealiMCP.Server.Api.Api.Auth.Logout;
using MealiMCP.Server.Api.Api.Auth.Oauth;
using MealiMCP.Server.Api.Api.Auth.Refresh;
using MealiMCP.Server.Api.Api.Auth.Token;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MealiMCP.Server.Api.Api.Auth
{
    /// <summary>
    /// Builds and executes requests for operations under \api\auth
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AuthRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The logout property</summary>
        public global::MealiMCP.Server.Api.Api.Auth.Logout.LogoutRequestBuilder Logout
        {
            get => new global::MealiMCP.Server.Api.Api.Auth.Logout.LogoutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauth property</summary>
        public global::MealiMCP.Server.Api.Api.Auth.Oauth.OauthRequestBuilder Oauth
        {
            get => new global::MealiMCP.Server.Api.Api.Auth.Oauth.OauthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refresh property</summary>
        public global::MealiMCP.Server.Api.Api.Auth.Refresh.RefreshRequestBuilder Refresh
        {
            get => new global::MealiMCP.Server.Api.Api.Auth.Refresh.RefreshRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The token property</summary>
        public global::MealiMCP.Server.Api.Api.Auth.Token.TokenRequestBuilder Token
        {
            get => new global::MealiMCP.Server.Api.Api.Auth.Token.TokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/auth", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Auth.AuthRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AuthRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/auth", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
