// <auto-generated/>
#pragma warning disable CS0618
using MealiMCP.Server.Api.Api.Recipes.Timeline.Events;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MealiMCP.Server.Api.Api.Recipes.Timeline
{
    /// <summary>
    /// Builds and executes requests for operations under \api\recipes\timeline
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TimelineRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The events property</summary>
        public global::MealiMCP.Server.Api.Api.Recipes.Timeline.Events.EventsRequestBuilder Events
        {
            get => new global::MealiMCP.Server.Api.Api.Recipes.Timeline.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Recipes.Timeline.TimelineRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TimelineRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/recipes/timeline", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Recipes.Timeline.TimelineRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TimelineRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/recipes/timeline", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
