// <auto-generated/>
#pragma warning disable CS0618
using MealiMCP.Server.Api.Api.Media.Docker;
using MealiMCP.Server.Api.Api.Media.Recipes;
using MealiMCP.Server.Api.Api.Media.Users;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MealiMCP.Server.Api.Api.Media
{
    /// <summary>
    /// Builds and executes requests for operations under \api\media
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MediaRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The docker property</summary>
        public global::MealiMCP.Server.Api.Api.Media.Docker.DockerRequestBuilder Docker
        {
            get => new global::MealiMCP.Server.Api.Api.Media.Docker.DockerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recipes property</summary>
        public global::MealiMCP.Server.Api.Api.Media.Recipes.RecipesRequestBuilder Recipes
        {
            get => new global::MealiMCP.Server.Api.Api.Media.Recipes.RecipesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::MealiMCP.Server.Api.Api.Media.Users.UsersRequestBuilder Users
        {
            get => new global::MealiMCP.Server.Api.Api.Media.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Media.MediaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MediaRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/media", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Media.MediaRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MediaRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/media", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
