// <auto-generated/>
#pragma warning disable CS0618
using MealiMCP.Server.Api.Api.App.About;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MealiMCP.Server.Api.Api.App
{
    /// <summary>
    /// Builds and executes requests for operations under \api\app
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AppRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The about property</summary>
        public global::MealiMCP.Server.Api.Api.App.About.AboutRequestBuilder About
        {
            get => new global::MealiMCP.Server.Api.Api.App.About.AboutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.App.AppRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AppRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/app", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.App.AppRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AppRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/app", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
