// <auto-generated/>
#pragma warning disable CS0618
using MealiMCP.Server.Api.Api.Users.Self.Favorites;
using MealiMCP.Server.Api.Api.Users.Self.Ratings;
using MealiMCP.Server.Api.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MealiMCP.Server.Api.Api.Users.Self
{
    /// <summary>
    /// Builds and executes requests for operations under \api\users\self
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SelfRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The favorites property</summary>
        public global::MealiMCP.Server.Api.Api.Users.Self.Favorites.FavoritesRequestBuilder Favorites
        {
            get => new global::MealiMCP.Server.Api.Api.Users.Self.Favorites.FavoritesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ratings property</summary>
        public global::MealiMCP.Server.Api.Api.Users.Self.Ratings.RatingsRequestBuilder Ratings
        {
            get => new global::MealiMCP.Server.Api.Api.Users.Self.Ratings.RatingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Users.Self.SelfRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SelfRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/users/self", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Users.Self.SelfRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SelfRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/users/self", rawUrl)
        {
        }
        /// <summary>
        /// Get Logged In User
        /// </summary>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.UserOut"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::MealiMCP.Server.Api.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MealiMCP.Server.Api.Models.UserOut?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MealiMCP.Server.Api.Models.UserOut> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::MealiMCP.Server.Api.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::MealiMCP.Server.Api.Models.UserOut>(requestInfo, global::MealiMCP.Server.Api.Models.UserOut.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get Logged In User
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Api.Users.Self.SelfRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MealiMCP.Server.Api.Api.Users.Self.SelfRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MealiMCP.Server.Api.Api.Users.Self.SelfRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class SelfRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
