// <auto-generated/>
#pragma warning disable CS0618
using MealiMCP.Server.Api.Api.Households.Shopping.Items;
using MealiMCP.Server.Api.Api.Households.Shopping.Lists;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MealiMCP.Server.Api.Api.Households.Shopping
{
    /// <summary>
    /// Builds and executes requests for operations under \api\households\shopping
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ShoppingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The items property</summary>
        public global::MealiMCP.Server.Api.Api.Households.Shopping.Items.ItemsRequestBuilder Items
        {
            get => new global::MealiMCP.Server.Api.Api.Households.Shopping.Items.ItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lists property</summary>
        public global::MealiMCP.Server.Api.Api.Households.Shopping.Lists.ListsRequestBuilder Lists
        {
            get => new global::MealiMCP.Server.Api.Api.Households.Shopping.Lists.ListsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Households.Shopping.ShoppingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ShoppingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/households/shopping", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Households.Shopping.ShoppingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ShoppingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/households/shopping", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
