// <auto-generated/>
#pragma warning disable CS0618
using MealiMCP.Server.Api.Api.Media.Recipes.Item.Images.Timeline.Item.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MealiMCP.Server.Api.Api.Media.Recipes.Item.Images.Timeline.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\media\recipes\{recipe_id}\images\timeline\{timeline_event_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTimeline_event_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the MealiMCP.Server.Api.api.media.recipes.item.images.timeline.item.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Api.Media.Recipes.Item.Images.Timeline.Item.Item.WithFile_nameItemRequestBuilder"/></returns>
        public global::MealiMCP.Server.Api.Api.Media.Recipes.Item.Images.Timeline.Item.Item.WithFile_nameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("file_name", position);
                return new global::MealiMCP.Server.Api.Api.Media.Recipes.Item.Images.Timeline.Item.Item.WithFile_nameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Media.Recipes.Item.Images.Timeline.Item.WithTimeline_event_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTimeline_event_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/media/recipes/{recipe_id}/images/timeline/{timeline_event_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Media.Recipes.Item.Images.Timeline.Item.WithTimeline_event_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTimeline_event_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/media/recipes/{recipe_id}/images/timeline/{timeline_event_id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
