// <auto-generated/>
#pragma warning disable CS0618
using MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.Item;
using MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.Suggestions;
using MealiMCP.Server.Api.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes
{
    /// <summary>
    /// Builds and executes requests for operations under \api\explore\groups\{group_slug}\recipes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RecipesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The suggestions property</summary>
        public global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.Suggestions.SuggestionsRequestBuilder Suggestions
        {
            get => new global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.Suggestions.SuggestionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the MealiMCP.Server.Api.api.explore.groups.item.recipes.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.Item.WithRecipe_slugItemRequestBuilder"/></returns>
        public global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.Item.WithRecipe_slugItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("recipe_slug", position);
                return new global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.Item.WithRecipe_slugItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.RecipesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RecipesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/explore/groups/{group_slug}/recipes{?categories*,cookbook*,foods*,households*,orderBy*,orderByNullPosition*,orderDirection*,page*,paginationSeed*,perPage*,queryFilter*,requireAllCategories*,requireAllFoods*,requireAllTags*,requireAllTools*,search*,tags*,tools*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.RecipesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RecipesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/explore/groups/{group_slug}/recipes{?categories*,cookbook*,foods*,households*,orderBy*,orderByNullPosition*,orderDirection*,page*,paginationSeed*,perPage*,queryFilter*,requireAllCategories*,requireAllFoods*,requireAllTags*,requireAllTools*,search*,tags*,tools*}", rawUrl)
        {
        }
        /// <summary>
        /// Get All
        /// </summary>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Models.PaginationBase_RecipeSummary_"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::MealiMCP.Server.Api.Models.HTTPValidationError">When receiving a 422 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MealiMCP.Server.Api.Models.PaginationBase_RecipeSummary_?> GetAsync(Action<RequestConfiguration<global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.RecipesRequestBuilder.RecipesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MealiMCP.Server.Api.Models.PaginationBase_RecipeSummary_> GetAsync(Action<RequestConfiguration<global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.RecipesRequestBuilder.RecipesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::MealiMCP.Server.Api.Models.HTTPValidationError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::MealiMCP.Server.Api.Models.PaginationBase_RecipeSummary_>(requestInfo, global::MealiMCP.Server.Api.Models.PaginationBase_RecipeSummary_.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get All
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.RecipesRequestBuilder.RecipesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.RecipesRequestBuilder.RecipesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.RecipesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.RecipesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.RecipesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get All
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RecipesRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("categories")]
            public string? Categories { get; set; }
#nullable restore
#else
            [QueryParameter("categories")]
            public string Categories { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cookbook")]
            public string? Cookbook { get; set; }
#nullable restore
#else
            [QueryParameter("cookbook")]
            public string Cookbook { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("foods")]
            public string? Foods { get; set; }
#nullable restore
#else
            [QueryParameter("foods")]
            public string Foods { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("households")]
            public string? Households { get; set; }
#nullable restore
#else
            [QueryParameter("households")]
            public string Households { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderBy")]
            public string? OrderBy { get; set; }
#nullable restore
#else
            [QueryParameter("orderBy")]
            public string OrderBy { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderByNullPosition")]
            public string? OrderByNullPosition { get; set; }
#nullable restore
#else
            [QueryParameter("orderByNullPosition")]
            public string OrderByNullPosition { get; set; }
#endif
            [Obsolete("This property is deprecated, use OrderDirectionAsOrderDirection instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderDirection")]
            public string? OrderDirection { get; set; }
#nullable restore
#else
            [QueryParameter("orderDirection")]
            public string OrderDirection { get; set; }
#endif
            [QueryParameter("orderDirection")]
            public global::MealiMCP.Server.Api.Models.OrderDirection? OrderDirectionAsOrderDirection { get; set; }
            [QueryParameter("page")]
            public int? Page { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("paginationSeed")]
            public string? PaginationSeed { get; set; }
#nullable restore
#else
            [QueryParameter("paginationSeed")]
            public string PaginationSeed { get; set; }
#endif
            [QueryParameter("perPage")]
            public int? PerPage { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("queryFilter")]
            public string? QueryFilter { get; set; }
#nullable restore
#else
            [QueryParameter("queryFilter")]
            public string QueryFilter { get; set; }
#endif
            [QueryParameter("requireAllCategories")]
            public bool? RequireAllCategories { get; set; }
            [QueryParameter("requireAllFoods")]
            public bool? RequireAllFoods { get; set; }
            [QueryParameter("requireAllTags")]
            public bool? RequireAllTags { get; set; }
            [QueryParameter("requireAllTools")]
            public bool? RequireAllTools { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search")]
            public string? Search { get; set; }
#nullable restore
#else
            [QueryParameter("search")]
            public string Search { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tags")]
            public string? Tags { get; set; }
#nullable restore
#else
            [QueryParameter("tags")]
            public string Tags { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tools")]
            public string? Tools { get; set; }
#nullable restore
#else
            [QueryParameter("tools")]
            public string Tools { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RecipesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::MealiMCP.Server.Api.Api.Explore.Groups.Item.Recipes.RecipesRequestBuilder.RecipesRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
