// <auto-generated/>
#pragma warning disable CS0618
using MealiMCP.Server.Api.Api.Admin.Debug.Openai;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MealiMCP.Server.Api.Api.Admin.Debug
{
    /// <summary>
    /// Builds and executes requests for operations under \api\admin\debug
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DebugRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The openai property</summary>
        public global::MealiMCP.Server.Api.Api.Admin.Debug.Openai.OpenaiRequestBuilder Openai
        {
            get => new global::MealiMCP.Server.Api.Api.Admin.Debug.Openai.OpenaiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Admin.Debug.DebugRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DebugRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/admin/debug", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Admin.Debug.DebugRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DebugRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/admin/debug", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
