// <auto-generated/>
#pragma warning disable CS0618
using MealiMCP.Server.Api.Api.Admin.About;
using MealiMCP.Server.Api.Api.Admin.Backups;
using MealiMCP.Server.Api.Api.Admin.Debug;
using MealiMCP.Server.Api.Api.Admin.Email;
using MealiMCP.Server.Api.Api.Admin.Groups;
using MealiMCP.Server.Api.Api.Admin.Households;
using MealiMCP.Server.Api.Api.Admin.Maintenance;
using MealiMCP.Server.Api.Api.Admin.Users;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MealiMCP.Server.Api.Api.Admin
{
    /// <summary>
    /// Builds and executes requests for operations under \api\admin
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AdminRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The about property</summary>
        public global::MealiMCP.Server.Api.Api.Admin.About.AboutRequestBuilder About
        {
            get => new global::MealiMCP.Server.Api.Api.Admin.About.AboutRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The backups property</summary>
        public global::MealiMCP.Server.Api.Api.Admin.Backups.BackupsRequestBuilder Backups
        {
            get => new global::MealiMCP.Server.Api.Api.Admin.Backups.BackupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The debug property</summary>
        public global::MealiMCP.Server.Api.Api.Admin.Debug.DebugRequestBuilder Debug
        {
            get => new global::MealiMCP.Server.Api.Api.Admin.Debug.DebugRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The email property</summary>
        public global::MealiMCP.Server.Api.Api.Admin.Email.EmailRequestBuilder Email
        {
            get => new global::MealiMCP.Server.Api.Api.Admin.Email.EmailRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The groups property</summary>
        public global::MealiMCP.Server.Api.Api.Admin.Groups.GroupsRequestBuilder Groups
        {
            get => new global::MealiMCP.Server.Api.Api.Admin.Groups.GroupsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The households property</summary>
        public global::MealiMCP.Server.Api.Api.Admin.Households.HouseholdsRequestBuilder Households
        {
            get => new global::MealiMCP.Server.Api.Api.Admin.Households.HouseholdsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The maintenance property</summary>
        public global::MealiMCP.Server.Api.Api.Admin.Maintenance.MaintenanceRequestBuilder Maintenance
        {
            get => new global::MealiMCP.Server.Api.Api.Admin.Maintenance.MaintenanceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::MealiMCP.Server.Api.Api.Admin.Users.UsersRequestBuilder Users
        {
            get => new global::MealiMCP.Server.Api.Api.Admin.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Admin.AdminRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdminRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/admin", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Admin.AdminRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AdminRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/admin", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
