// <auto-generated/>
#pragma warning disable CS0618
using MealiMCP.Server.Api.Api.Users.ApiTokens;
using MealiMCP.Server.Api.Api.Users.ForgotPassword;
using MealiMCP.Server.Api.Api.Users.Item;
using MealiMCP.Server.Api.Api.Users.Password;
using MealiMCP.Server.Api.Api.Users.Register;
using MealiMCP.Server.Api.Api.Users.ResetPassword;
using MealiMCP.Server.Api.Api.Users.Self;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MealiMCP.Server.Api.Api.Users
{
    /// <summary>
    /// Builds and executes requests for operations under \api\users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The apiTokens property</summary>
        public global::MealiMCP.Server.Api.Api.Users.ApiTokens.ApiTokensRequestBuilder ApiTokens
        {
            get => new global::MealiMCP.Server.Api.Api.Users.ApiTokens.ApiTokensRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The forgotPassword property</summary>
        public global::MealiMCP.Server.Api.Api.Users.ForgotPassword.ForgotPasswordRequestBuilder ForgotPassword
        {
            get => new global::MealiMCP.Server.Api.Api.Users.ForgotPassword.ForgotPasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The password property</summary>
        public global::MealiMCP.Server.Api.Api.Users.Password.PasswordRequestBuilder Password
        {
            get => new global::MealiMCP.Server.Api.Api.Users.Password.PasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The register property</summary>
        public global::MealiMCP.Server.Api.Api.Users.Register.RegisterRequestBuilder Register
        {
            get => new global::MealiMCP.Server.Api.Api.Users.Register.RegisterRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The resetPassword property</summary>
        public global::MealiMCP.Server.Api.Api.Users.ResetPassword.ResetPasswordRequestBuilder ResetPassword
        {
            get => new global::MealiMCP.Server.Api.Api.Users.ResetPassword.ResetPasswordRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The self property</summary>
        public global::MealiMCP.Server.Api.Api.Users.Self.SelfRequestBuilder Self
        {
            get => new global::MealiMCP.Server.Api.Api.Users.Self.SelfRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the MealiMCP.Server.Api.api.users.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Api.Users.Item.ItemRequestBuilder"/></returns>
        public global::MealiMCP.Server.Api.Api.Users.Item.ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("%2Did", position);
                return new global::MealiMCP.Server.Api.Api.Users.Item.ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/users", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/users", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
