// <auto-generated/>
#pragma warning disable CS0618
using MealiMCP.Server.Api.Api.Recipes.Create.HtmlOrJson;
using MealiMCP.Server.Api.Api.Recipes.Create.Image;
using MealiMCP.Server.Api.Api.Recipes.Create.Url;
using MealiMCP.Server.Api.Api.Recipes.Create.Zip;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MealiMCP.Server.Api.Api.Recipes.Create
{
    /// <summary>
    /// Builds and executes requests for operations under \api\recipes\create
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The htmlOrJson property</summary>
        public global::MealiMCP.Server.Api.Api.Recipes.Create.HtmlOrJson.HtmlOrJsonRequestBuilder HtmlOrJson
        {
            get => new global::MealiMCP.Server.Api.Api.Recipes.Create.HtmlOrJson.HtmlOrJsonRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The image property</summary>
        public global::MealiMCP.Server.Api.Api.Recipes.Create.Image.ImageRequestBuilder Image
        {
            get => new global::MealiMCP.Server.Api.Api.Recipes.Create.Image.ImageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The url property</summary>
        public global::MealiMCP.Server.Api.Api.Recipes.Create.Url.UrlRequestBuilder Url
        {
            get => new global::MealiMCP.Server.Api.Api.Recipes.Create.Url.UrlRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The zip property</summary>
        public global::MealiMCP.Server.Api.Api.Recipes.Create.Zip.ZipRequestBuilder Zip
        {
            get => new global::MealiMCP.Server.Api.Api.Recipes.Create.Zip.ZipRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Recipes.Create.CreateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CreateRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/recipes/create", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Recipes.Create.CreateRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CreateRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/recipes/create", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
