// <auto-generated/>
#pragma warning disable CS0618
using MealiMCP.Server.Api.Api.Households.RecipeActions.Item.Trigger.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MealiMCP.Server.Api.Api.Households.RecipeActions.Item.Trigger
{
    /// <summary>
    /// Builds and executes requests for operations under \api\households\recipe-actions\{item_id}\trigger
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TriggerRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the MealiMCP.Server.Api.api.households.recipeActions.item.trigger.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::MealiMCP.Server.Api.Api.Households.RecipeActions.Item.Trigger.Item.WithRecipe_slugItemRequestBuilder"/></returns>
        public global::MealiMCP.Server.Api.Api.Households.RecipeActions.Item.Trigger.Item.WithRecipe_slugItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("recipe_slug", position);
                return new global::MealiMCP.Server.Api.Api.Households.RecipeActions.Item.Trigger.Item.WithRecipe_slugItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Households.RecipeActions.Item.Trigger.TriggerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TriggerRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/households/recipe-actions/{item_id}/trigger", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MealiMCP.Server.Api.Api.Households.RecipeActions.Item.Trigger.TriggerRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TriggerRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/households/recipe-actions/{item_id}/trigger", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
